[build]
publish = "Evera"

[build.environment]
NODE_VERSION = "22"

# Optional headers
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "SAMEORIGIN"
Referrer-Policy = "strict-origin-when-cross-origin"
