[build]
  base = ""
  publish = "."
  command = ""

[build.environment]
  NODE_VERSION = "18"

# Если сайт МНОГОСТРАНИЧНЫЙ (каждая страница – свой .html), редирект ниже НЕ НУЖЕН.
# Если когда-нибудь превратим главную в SPA — тогда раскомментируем:
/*
#[[redirects]]
#  from = "/*"
#  to = "/index.html"
#  status = 200
*/
